sudo: false

branches:
  only:
    - master
    - /^v\d+(\.\d+)*$/

# turn shallow clone off for sonar
git:
  depth: false

language: java

addons:
  sonarcloud:
    organization: "simplify4u"

install:
    - mkdir -p ../utils
    - curl -Ls https://github.com/s4u/travis/archive/master.tar.gz |
        tar -zx --strip-components 2 -C ../utils travis-master/src

before_script:
  - ../utils/print-env.sh

jobs:
  include:
    - name: "jdk8"
      jdk: openjdk8
      script: >-
        ../utils/mvn-push.sh    clean deploy &&
        ../utils/mvn-pr.sh      clean verify &&
        ../utils/mvn-sonar.sh   sonar:sonar
      if: repo = "s4u/parent"

    - name: "jdk8 - forks"
      jdk: openjdk8
      script:
        - ../utils/mvn-run.sh clean verify
      if: repo != "s4u/parent"

    - name: "jdk11"
      jdk: openjdk11
      script:
        - ../utils/mvn-run.sh clean verify

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

before_cache:
  - rm -rfv $HOME/.m2/repository/org/simplify4u/parent*
